twig:
  default_path: "%kernel.project_dir%/templates"
  globals:
    locales: '%locales%'
  form_themes:
    - "bootstrap_5_horizontal_layout.html.twig"
    - 'forms/radiobutton.html.twig'
    - 'forms/choicewidgetexpanded.html.twig'
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  paths:
    '%kernel.project_dir%/public/images': images
    '%kernel.project_dir%/icons': icons
    '%kernel.project_dir%/public/images/clans': clans
when@test:
  twig:
    strict_variables: true