FROM nginx:latest

COPY build/nginx/default.conf /etc/nginx/conf.d/

RUN echo "upstream php-upstream { server php:9000; }" > /etc/nginx/conf.d/upstream.conf

RUN usermod -u 1000 www-data
# RUN adduser -D -g '' -G www-data www-data
#CMD ["nginx"]
# EXPOSE 80
# EXPOSE 443